theme: minima
title: DevOps Tools
description: Discover a Tool Everyday
skin: dark
logo: /assets/img/logo.png
header_pages:
  - about.md
author: KK

minima:
  social_links:
    github:  kavinksm

plugins:
 - jekyll-seo-tag