theme: minima
title: DevOps Tools
description: Discover a Tool Everyday
logo: /assets/img/logo.png
header_pages:
  - about.md
author: KK

minima:
  skin: dark
  social_links:
    github: kavinksm

plugins:
 - jekyll-seo-tag