theme: minima
title: DevOps Tools
description: Discover a Tool Everyday
logo: /assets/img/logo.png
header_pages:
  - about.md
author: KK

social:
  name: kavin
  links:
    - https://github.com/kavinksm

plugins:
 - jekyll-seo-tag